### ISSUE TITLE
The indexing check on line 151 of video_dataset.py

### ISSUE THREAD

**Issue by 1014393927** [qiuyu96/CoDeF#12]
'flows': self.all_flows[idx] if (idx<len(self.all_images)-2)&(self.all_flows is not None) else -1e5,
The index check here may be incorrect, causing the index to exceed the list range. I suggest making the following modifications:
'flows': self.all_flows[idx] if (idx < len(self.all_images) - 2) and (self.all_flows is not None) and (idx < len(self.all_flows)) else -1e5,

**Comment by FSYFSYFSY** [comment]
How did you fix this problem? I was also encountering this issues when I try to use my own image as trainning dataset

**Comment by FSYFSYFSY** [comment]
> 
I found the reason, it was due to I was copying the wrong config yaml file as training file. The right format of training config should be as same as lemon_hit.yaml
