### ISSUE TITLE
 [Errno 32] Broken pipe - ffmpeg

### ISSUE THREAD

**Issue by junghyeon0427** [qiuyu96/CoDeF#13]
Hi, I have some question when using a custom dataset. I completed training well and got a checkpoint, but the following Broken pipe error occurred during the test. How can I solve it?
![Screenshot from 2023-08-18 15-39-41](https://github.com/qiuyu96/CoDeF/assets/77001598/cd1466c7-fa79-4f7d-8643-e4f047a8562e)

**Comment by Simi-pri** [comment]
1. Make sure you have the latest version of the skvideo library. You can update skvideo by running the following command:

```shell
pip install --upgrade sk-video
```

2. Check if your ffmpeg has been compiled with the necessary components, such as libx264. If not, you'll need to recompile or reinstall ffmpeg. I resolved the issue by reinstalling ffmpeg. To reinstall ffmpeg on Ubuntu, you can use the following commands. Please note that it may take some time:
```shell
apt-get -y install software-properties-common
add-apt-repository ppa:jonathonf/ffmpeg-4
apt-get update
apt-get -y install ffmpeg
```

**Comment by vivounicorn** [comment]
If you use conda, it is likely that conda's ffmpeg conflicts with:
/usr/bin/ffmpeg

you can uninstall: 
conda uninstall ffmpeg

**Comment by Pythonpa** [comment]
> 1. Make sure you have the latest version of the skvideo library. You can update skvideo by running the following command:确保您拥有最新版本的 skvideo 库。您可以通过运行以下命令来更新 skvideo：
> 
> ```shell
> pip install --upgrade sk-video
> ```
> 
> 2. Check if your ffmpeg has been compiled with the necessary components, such as libx264. If not, you'll need to recompile or reinstall ffmpeg. I resolved the issue by reinstalling ffmpeg. To reinstall ffmpeg on Ubuntu, you can use the following commands. Please note that it may take some time:检查您的 ffmpeg 是否已使用必要的组件进行编译，例如 libx264。如果没有，您需要重新编译或重新安装 ffmpeg。我通过重新安装 ffmpeg 解决了这个问题。要在 Ubuntu 上重新安装 ffmpeg，可以使用以下命令。请注意，这可能需要一些时间：
> 
> ```shell
> apt-get -y install software-properties-common
> add-apt-repository ppa:jonathonf/ffmpeg-4
> apt-get update
> apt-get -y install ffmpeg
> ```

weird，it told me this:
(codef) po@P:~/CoDeF$ sudo add-apt-repository ppa:jonathonf/ffmpeg-4
 Backport of FFmpeg 4 and associated libraries. Now includes AOM/AV1 support!

FDK AAC is not compatible with GPL and FFmpeg can't be redistributed with it included. Please don't ask for it to be added to this public PPA.

---

PPA supporters:

BigBlueButton (https://bigbluebutton.org)

---

Donate to FFMPEG: https://ffmpeg.org/donations.html
Donate to Debian: https://www.debian.org/donations
Donate to this PPA: https://ko-fi.com/jonathonf
 More info: https://launchpad.net/~jonathonf/+archive/ubuntu/ffmpeg-4
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Get:1 file:/var/cuda-repo-wsl-ubuntu-11-8-local  InRelease [1575 B]
Get:2 file:/var/cudnn-local-repo-ubuntu2004-8.9.3.28  InRelease [1572 B]
Get:1 file:/var/cuda-repo-wsl-ubuntu-11-8-local  InRelease [1575 B]
Get:2 file:/var/cudnn-local-repo-ubuntu2004-8.9.3.28  InRelease [1572 B]
Hit:3 http://security.ubuntu.com/ubuntu focal-security InRelease    
Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease              
Ign:5 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu focal InRelease
Hit:6 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Err:8 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu focal Release
  404  Not Found [IP: 198.18.2.217 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
