### ISSUE TITLE
How to generate video  Optical flow  and masks？

### ISSUE THREAD

**Issue by 1014393927** [qiuyu96/CoDeF#16]
Is there any supported code for this project？

**Comment by jfischoff** [comment]
I assume Raft was used for the optical flow. My question is what resolution and should the optical flow be computed from a single canonical frame, or should we do subsequent frame diffs for the optical flow?

**Comment by lininghuhu** [comment]
这是来自QQ邮箱自动回复邮件。你好，我已收到你的邮件。

**Comment by ken-ouyang** [comment]
Hi, we are planning to release the preprocess scripts very soon. Please stay tuned.

**Comment by qiuyu96** [comment]
Hi, we have uploaded data preprocessing scripts. See details [here](https://github.com/qiuyu96/CoDeF#customize-your-own-data) .
