### ISSUE TITLE
About tinycudann

### ISSUE THREAD

**Issue by Felix20021231** [qiuyu96/CoDeF#18]
I want to use my new video to train, I had prepared the environment and installed the requirement libraries. But after running the comand **`sh scripts/train_multi.sh`**, I face the problem **`No module named 'tinycudann'`**, and I try to use pip/pip3/conda to install it, however it can not be found. I want to kown how to deal with it?

**Comment by ESK-01** [comment]
https://github.com/NVlabs/tiny-cuda-nn

**Comment by qiuyu96** [comment]
Please refer to https://github.com/NVlabs/tiny-cuda-nn#pytorch-extension for `tiny-cuda-nn` installation.
