### ISSUE TITLE
train.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by lizhenhuiya** [qiuyu96/CoDeF#19]
./scripts/test_canonical.sh

train.py': [Errno 2] No such file or directory

<img width="375" alt="image" src="https://github.com/qiuyu96/CoDeF/assets/85615153/81c798c8-c8ad-4159-9e37-d180c8943c10">

**Comment by ESK-01** [comment]
Copy test_ The canonical.sh file is run in the root directory
