### ISSUE TITLE
video length

### ISSUE THREAD

**Issue by zcdliuwei** [qiuyu96/CoDeF#2]
thanks for your great work!
May I ask how long video length this method can support？

**Comment by henry123-boy** [comment]
Hi, thank you noticing our work. 
For your question, the maximum video length we had tried is around 15s-20s (60fps). And for longer video, you can try to adjust some key `hyper-parameters` "Including but not limited to：

- the size of hash table
- the depth and width of MLP
- the maximum training time

However, one more thing need to be noticed: the video has better exclude those complex 3D-aware rotation, where the content of video is not easily flattened into a 2D field.  In this cases, we recommend to split the whole video into several fragments.

**Comment by zcdliuwei** [comment]
> 

Thank you very much for your detailed reply！
Looking forward to customizing personal data section， thanks again！
