### ISSUE TITLE
URL for data downloading is invalid

### ISSUE THREAD

**Issue by weTerence** [qiuyu96/CoDeF#21]
![image](https://github.com/qiuyu96/CoDeF/assets/38182430/138855e1-81d5-4267-ab9e-741e4b079784)

**Comment by qiuyu96** [comment]
The URL is still functioning properly for me. I suggest refreshing the page or attempting to access it again after a short wait.

**Comment by yaboojia** [comment]
I also meet this suitation and can't address.

**Comment by qiuyu96** [comment]
Hi, sorry for the error. I have updated the [URL](https://drive.google.com/file/d/10Msz37MpjZQFPXlDWCZqrcQjhxpQSvCI/view?usp=sharing) for data downloading.
