### ISSUE TITLE
请问获取optical flow图片之后，如何获取类似beauty_0_flow文件夹中的.npy文件？

### ISSUE THREAD

**Issue by ZJ-CAI** [qiuyu96/CoDeF#33]
I have extracted the optical flow by RAFT. Could you show me how to get the xxx.npy like those in beauty_0_flow and xxx_c.npy in  beauty_0_flow_confidence?

Thank you

**Comment by qiuyu96** [comment]
Hi, we have uploaded data preprocessing scripts. See details [here](https://github.com/qiuyu96/CoDeF#customize-your-own-data).
