### ISSUE TITLE
can you provide the docker image?

### ISSUE THREAD

**Issue by yfq512** [qiuyu96/CoDeF#34]
thanks your code, can you provide the docker image to run code?

**Comment by ken-ouyang** [comment]
At present, our primary focus is on the Gradio version on Hugging Face. As such, the development and release of a Docker image is not in our immediate plans. However, we appreciate the importance of a Docker image for many users and understand the flexibility and convenience it provides. Therefore, we are open to the possibility of adding it in the future, once we have completed the Web version. Please stay tuned.

**Comment by Jackylee2032** [comment]
Do you have hf demo now？

**Comment by ken-ouyang** [comment]
@Jackylee2032 Just start working on it. We will release the HF demo in a few days.
