### ISSUE TITLE
with masks test_canonical.sh report error : expected grid and input to have same batch size

### ISSUE THREAD

**Issue by oceanheart** [qiuyu96/CoDeF#42]
File "D:\workspace\CoDeF\train.py", line 214, in forward
    results = torch.nn.functional.grid_sample(
  File "C:\Users\ASUS\anaconda3\lib\site-packages\torch\nn\functional.py", line 4244, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
RuntimeError: grid_sampler(): expected grid and input to have same batch size, but got input with sizes [0, 3, 540, 540] and grid with sizes [1, 291600, 1, 2]

But if I config mask_dir= null， the code runs well.

**Comment by sigrace1111** [comment]
same error

**Comment by FSYFSYFSY** [comment]
Got same error

**Comment by rainsoulsrx** [comment]
same error

**Comment by qiuyu96** [comment]
Hi, sorry for the error. I have updated the mask preprocessing script [here](https://github.com/qiuyu96/CoDeF/blob/main/data_preprocessing/preproc_mask.py).

**Comment by zhanghongyong123456** [comment]
> Hi, sorry for the error. I have updated the mask preprocessing script [here](https://github.com/qiuyu96/CoDeF/blob/main/data_preprocessing/preproc_mask.py).

NO， Still have this problem,

**Comment by FSYFSYFSY** [comment]
seems still doesn't work

**Comment by qiuyu96** [comment]
I think I have identified the issue. When using masks, multiple canonical images will be generated. Please verify the contents of your result folder after running `./scripts/test_multi.sh`, you should find `canonical_0.png` and `canonical_1.png` files. Please ensure that **all** canonical images are placed in the `base_control` folder.

**Comment by rainsoulsrx** [comment]
> I got canonical_0.png and canonical_1.png, so when I run test video translation step, I need translate both of them using  text prompts?

**Comment by zhanghongyong123456** [comment]
> I think I have identified the issue. When using masks, multiple canonical images will be generated. Please verify the contents of your result folder after running `./scripts/test_multi.sh`, you should find `canonical_0.png` and `canonical_1.png` files. Please ensure that **all** canonical images are placed in the `base_control` folder.

There will be two faces in the video
![image](https://github.com/qiuyu96/CoDeF/assets/48466610/f3681e0b-7be0-4992-815f-4af2b70d2efa)

**Comment by qiuyu96** [comment]
> > I got canonical_0.png and canonical_1.png, so when I run test video translation step, I need translate both of them using  text prompts?

It depends on your requirements. If you intend to transfer the entire video, you should transfer both canonical images. However, if you only wish to transfer the foreground of the video sequences, you will only need to transfer `canonical_0.png`.

**Comment by ChdDongyang** [comment]
> > > I got canonical_0.png and canonical_1.png, so when I run test video translation step, I need translate both of them using  text prompts?
> 
> It depends on your requirements. If you intend to transfer the entire video, you should transfer both canonical images. However, if you only wish to transfer the foreground of the video sequences, you will only need to transfer `canonical_0.png`.

Hello，if I put the thranfered canonical images both "canonical_0_transfered.png" and "canonical_1_transfered.png" to the dir all_sequences/$NAME/$EXP_NAME_control. How will the program distinguish between foreground and background? Is it based on naming or can it be automatically recognized？
