### ISSUE TITLE
效果调优请教

### ISSUE THREAD

**Issue by ltm920716** [qiuyu96/CoDeF#46]
你好，
本地尝试了一些视频，效果不是很稳定，请教一下看是哪里出了问题

第一个视频，46帧，视频画面基本不变，效果还是很稳定的
https://github.com/qiuyu96/CoDeF/assets/12007227/4cceed26-5d16-4770-88b2-f35ee1bf8b9a

第二个视频，64帧，即使用了flow和masks依然效果不好，提取的canonical图片也不是很好，下边分别是提取的canonical图，基于canonical的重构结果，以及转换结果（这是没有用flow和mask的结果，用了提升也很小，参数用的默认）
![canonical_0 (3)](https://github.com/qiuyu96/CoDeF/assets/12007227/e5b8222a-558b-4605-b7fe-487a4c39e89b)
https://github.com/qiuyu96/CoDeF/assets/12007227/dd128b1b-bee9-4888-8a1f-e927d5eadcf3
https://github.com/qiuyu96/CoDeF/assets/12007227/6bba232b-2f36-4d31-bd22-e5eb97ec2521

第三个视频，300帧，是第二个视频的加长版本，这次提取的canonical图片就更乱了，重构的视频水影严重，转换的视频画面也不动了（训练step用了50000）
![canonical_0 (1)](https://github.com/qiuyu96/CoDeF/assets/12007227/1703e8dd-139e-4855-bf47-b8d4209798e2)
![image](https://github.com/qiuyu96/CoDeF/assets/12007227/548dc4b5-9e36-4fae-a625-5910d301aece)
https://github.com/qiuyu96/CoDeF/assets/12007227/2d77d41d-41b4-43b8-ae30-8404f52a27eb

总体而言，加了flow的效果会有提升，加了mask的提升不如flow，视频动作稍快一些，canonical的提取就明显的差了，请教一下如何能保持效果相对稳定一些，谢谢

**Comment by ken-ouyang** [comment]
Please refer to the discussion in https://github.com/qiuyu96/CoDeF/issues/31. 

Currently the model does not support multiple canonical so it is hard to support long video. For the second video, the reconstruction quality is actually not that bad. You need to check out whether the translated canonical image align with the original canonical.
