### ISSUE TITLE
unable to download the video data provided 

### ISSUE THREAD

**Issue by zcuuu** [qiuyu96/CoDeF#47]

**Comment by zcuuu** [comment]
Provided data
We have provided some videos [here](https://drive.google.com/file/d/1cKZF6ILeokCjsSAGBmummcQh0uRGaC_F/view?usp=sharing) for quick test. Please download and unzip the data and put them in the root directory. More videos can be downloaded [here](https://drive.google.com/file/d/10Msz37MpjZQFPXlDWCZqrcQjhxpQSvCI/view?usp=sharing).



![image](https://github.com/qiuyu96/CoDeF/assets/44340519/e7361608-544c-4379-aac7-4827f3490de1)

**Comment by ken-ouyang** [comment]
The link works for me. Please refresh or try to download it later.
