### ISSUE TITLE
 About Training Model Hyperparameters Settings？

### ISSUE THREAD

**Issue by zhanghongyong123456** [qiuyu96/CoDeF#48]
May I ask if you will publish a document about training hyperparameter settings. I found that many people are asking about long videos and fast exercise training skills. I saw your reply, but we don’t know how to set them up

![image](https://github.com/qiuyu96/CoDeF/assets/48466610/66b66089-c26a-4a92-a934-0995a779f988)
![image](https://github.com/qiuyu96/CoDeF/assets/48466610/fbf9137f-8e68-420f-8c37-528583c4c16d)
![image](https://github.com/qiuyu96/CoDeF/assets/48466610/31b53196-e90d-474a-b643-bb562e417e7e)
![image](https://github.com/qiuyu96/CoDeF/assets/48466610/7cd19955-72e1-4ed6-9ca2-0ed944de2d94)

and    I found this question link crashed, here is why
https://github.com/qiuyu96/CoDeF/issues/39

**Comment by ken-ouyang** [comment]
We're considering the addition of a new section in the README dedicated to providing small tips for improved training. This will serve as a helpful guide, especially for users who are new to the system or those who want to optimize their training process.

However, we strongly encourage users to read the accompanying research paper to understand the fundamental concepts behind each hyperparameter. Gaining a thorough understanding of these underlying principles will equip you with the intuition needed to troubleshoot and resolve any issues that might arise during the training process.
