### ISSUE TITLE
bad canonical image?

### ISSUE THREAD

**Issue by rainsoulsrx** [qiuyu96/CoDeF#49]
Hi, I test reconstruction using this video, though reconstruction is ok, but I get strange canonical image as follows

https://github.com/qiuyu96/CoDeF/assets/24955512/d9fddcb5-dc37-4b63-8e47-2560e05d9a29

![image](https://github.com/qiuyu96/CoDeF/assets/24955512/489b82e2-b989-4c05-9958-dd66bb119619)

**Comment by ken-ouyang** [comment]
Please refer to https://github.com/qiuyu96/CoDeF/issues/31. 

I have a few additional suggestions that might help enhance your results:

1. Consider segmenting the objects initially. This approach can help prevent unusual, isolated boundaries from appearing in the canonical images, which could lead to more accurate reconstruction.

2. For the sequence you're working with, using two canonical images might yield better results. We're currently in the process of integrating 3D-awareness into the structure, which should further improve the outcomes.

3. Despite these potential improvements, it's worth noting that your current reconstruction seems to be of good quality. Therefore, you might still want to proceed with editing and then observe the translated results.

**Comment by pHaeusler** [comment]
@rainsoulsrx  - I have some notes that might help https://philliphaeusler.com/posts/codef/
https://github.com/pHaeusler/codef-experiments

**Comment by jetterson** [comment]
@rainsoulsrx Did you try to reconstruct the video use the canonical image you have get? I tried but the performance of the output video is bad, if you meet the same problem?
