### ISSUE TITLE
Which model to extract optical flow?

### ISSUE THREAD

**Issue by JC1DA** [qiuyu96/CoDeF#5]
Hi, thanks for your great work. Just curious which model you used to extract optical flow used in this system?

**Comment by qiuyu96** [comment]
Thanks for your attention. We use [RAFT](https://github.com/princeton-vl/RAFT) to extract optical flow. For more details, please refer to Section 3.2 of our [paper](https://arxiv.org/pdf/2308.07926.pdf).

**Comment by pHaeusler** [comment]
Are there instructions for how you used RAFT to generate the flow? Same for SAM-track
Thanks!

**Comment by lininghuhu** [comment]
> Are there instructions for how you used RAFT to generate the flow? Same for SAM-track Thanks!

do you get the instructions?

**Comment by jfischoff** [comment]
@qiuyu96 in the section 3.2 of your paper you explain how to make the confidence maps. However, there is a hyper parameter to the threshold the maps. What value did you use in your examples?

**Comment by iceflame89** [comment]
In the paper section 3.2, How to do Warp?
