### ISSUE TITLE
RuntimeError: grid_sampler(): expected grid and input to have same batch size, but got input with sizes [0, 3, 1024, 1024] and grid with sizes [1, 1048576, 1, 2]

### ISSUE THREAD

**Issue by WellTung666** [qiuyu96/CoDeF#51]
Hello! when I ran ./scripts/test_canonical.sh using My own model, the following error occurred. How can I solve this problem? Thanks~
`RuntimeError: grid_sampler(): expected grid and input to have same batch size, but got input with sizes [0, 3, 1024, 1024] and grid with sizes [1, 1048576, 1, 2]
`

**Comment by potoyeee** [comment]
Hello, i have this problem too. Did you fix it？

**Comment by Pythonpa** [comment]
The same......

**Comment by WellTung666** [comment]
> Hello, i have this problem too. Did you fix it？

I try to placed the canonical images in the base_control folder can solve this problem, but the final result was very poor.

**Comment by WellTung666** [comment]
> The same......

https://github.com/qiuyu96/CoDeF/issues/51#issuecomment-1696888500

**Comment by Pythonpa** [comment]
ah，it worked...
