### ISSUE TITLE
Question about Canonical Step

### ISSUE THREAD

**Issue by CharmsGraker** [qiuyu96/CoDeF#52]
Thanks for great work!
I notice all images in transformed video are warped by the first transformed img], aka `canonical_img`, which makes me little confused.
[code link ](https://github.com/qiuyu96/CoDeF/blob/137f16c5423d484846857327597bf65c06b92994/train.py#L205C1-L206C1)
I'm wondering the case like people turning around could be well handled by this field.

**Comment by ken-ouyang** [comment]
I think the turning around case might not work well with only one canonical presented. We are currently working on the improved version specifically designed for human. Please stay tuned.
