### ISSUE TITLE
请教如何做一个新的视频风格转换？

### ISSUE THREAD

**Issue by yinjiaoyuan** [qiuyu96/CoDeF#57]
您好！我已经在英伟达显卡的服务器上构建好本项目，而且也跑了./scripts/test_multi.sh和./scripts/test_canonical.sh可以看到结果与预期的效果是一致的，但是我不知道如何用我自己的视频来做这个风格转换。请问用我自己的视频来做风格转换需要哪些步骤？谢谢。

**Comment by ken-ouyang** [comment]
只需要把你得到的canonical image过一下controlnet或者其他风格转换工具（注意最好要对齐），然后把转换后的图放在test_canonical.sh中对应的文件夹，重新跑./scripts/test_canonical.sh即可。

**Comment by yinjiaoyuan** [comment]
那canonical image是如何得到的呢？

**Comment by yishuaidu** [comment]
> 

你跑test那个就有

**Comment by yinjiaoyuan** [comment]
我是跑通了test，效果也是有了，但是我想用自己的mp4视频来做一个自己的视频风格转换，不知道如何下手，请问具体步骤是什么？难道每个视频我都要训练一次吗？谢谢。
