### ISSUE TITLE
Equation 5

### ISSUE THREAD

**Issue by amitabe** [qiuyu96/CoDeF#9]
In equation (5) you mention `w` as a function of `j,k` but only `j` appears in the equation:

![image](https://github.com/qiuyu96/CoDeF/assets/97161908/c6d4c5d8-af9b-48d6-861d-da7aa4216a5c)

So how `k` plays a role in it?

**Comment by fenglinglwb** [comment]
From my understanding, it should be $\frac{1-{\rm cos}(\pi \cdot {\rm clamp}(m(k-N_{beg})/N_{step}-j, 0, 1))}{2}$

**Comment by ken-ouyang** [comment]
Thanks for pointing out the mistakes. We will update the paper. The formula stated by @fenglinglwb is correct.

**Comment by JiaHeng-DLUT** [comment]
What does `j` mean? And where is `l`?

**Comment by qiuyu96** [comment]
> What does `j` mean? And where is `l`?

Sorry for the mistake in the paper, it should be the $j^{th}$ layer.
